#
# © 2026-present https://github.com/cengiz-pz
#

pluginNodeName=Deeplink
pluginModuleName=deeplink
pluginPackage=org.godotengine.plugin.deeplink
pluginVersion=5.3
godotVersion=4.6
godotReleaseType=stable
extra.activityClass=org.godotengine.plugin.deeplink.DeeplinkActivity
gradleProjectName=godot-deeplink-plugin
